name: SensorLibrary
main: org.redstonechips.sensorlibrary.SensorLibrary
version: 0.40
api-version: 1.15
author: eisental
description: Sensor library for RedstoneChips integrated circuits plugin.
website: eisental.github.com/RedstoneChips
depend: [RedstoneChips]

